import { Injectable } from '@angular/core';
import { Book, Book as BookModel } from './book.model';

@Injectable({
  providedIn: 'root'
})
export class BookService {
  private books: BookModel[] = [
    { id: 1, title: 'The Lord of the Rings', author: 'J.R.R. Tolkien', category: 'Fiction', pageNumber: 200, publishingYear: 2022, description: 'In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell by chance into the hands of the hobbit Bilbo Baggins. From Saurons fastness in the Dark Tower of Mordor, his power spread far and wide. Sauron gathered all the Great Rings, but always he searched for the One Ring that would complete his dominion. Then Bilbo reached his eleventy-first birthday he disappeared, bequeathing to his young cousin Frodo the Ruling Ring and a perilous quest: to journey across Middle-earth, deep into the shadow of the Dark Lord, and destroy the Ring by casting it into the Cracks of Doom. The Lord of the Rings tells of the great quest undertaken by Frodo and the Fellowship of the Ring: Gandalf the Wizard; the hobbits Merry, Pippin, and Sam; Gimli the Dwarf; Legolas the Elf; Boromir of Gondor; and a tall, mysterious stranger called Strider.', price: 24.99, image: 'assets/book1.jpg', rating: 19, ratingsCount: 4 },
    { id: 2, title: 'The Wager', author: 'David Grann', category: 'Novel', pageNumber: 352, publishingYear: 2023, description: 'On January 28, 1742, a ramshackle vessel of patched-together wood and cloth washed up on the coast of Brazil. Inside were thirty emaciated men, barely alive, and they had an extraordinary tale to tell. They were survivors of His Majesty’s Ship the Wager, a British vessel that had left England in 1740 on a secret mission during an imperial war with Spain. While the Wager had been chasing a Spanish treasure-filled galleon known as “the prize of all the oceans,” it had wrecked on a desolate island off the coast of Patagonia. The men, after being marooned for months and facing starvation, built the flimsy craft and sailed for more than a hundred days, traversing nearly 3,000 miles of storm-wracked seas. They were greeted as heroes. But then ... six months later, another, even more decrepit craft landed on the coast of Chile. This boat contained just three castaways, and they told a very different story. The thirty sailors who landed in Brazil were not heroes – they were mutineers. The first group responded with countercharges of their own, of a tyrannical and murderous senior officer and his henchmen. It became clear that while stranded on the island the crew had fallen into anarchy, with warring factions fighting for dominion over the barren wilderness... ', price: 16.99, image: 'assets/book2.jpg', rating: 14, ratingsCount: 3 },
    { id: 3, title: 'Death on the Nile', author: 'Agatha Christie', category: 'Mystery', pageNumber: 352, publishingYear: 1937, description: 'The tranquility of a luxury cruise along the Nile was shattered by the discovery that Linnet Ridgeway had been shot through the head. She was young, stylish, and beautiful. A girl who had everything . . . until she lost her life. Hercule Poirot recalled an earlier outburst by a fellow passenger: “I’d like to put my dear little pistol against her head and just press the trigger.” Yet under the searing heat of the Egyptian sun, nothing is ever quite what it seems. A sweeping mystery of love, jealousy, and betrayal, Death on the Nile is one of Christie’s most legendary and timeless works.', price: 11.79, image: 'assets/book3.jpg', rating: 24, ratingsCount: 5 },
    { id: 4, title: 'Murder on Orient Express', author: 'Agatha Christie', category: 'Mystery', pageNumber: 288, publishingYear: 1934, description: 'THE MOST WIDELY READ MYSTERY OF ALL TIME—NOW A MAJOR MOTION PICTURE DIRECTED BY KENNETH BRANAGH AND PRODUCED BY RIDLEY SCOTT! “The murderer is with us—on the train now . . .” Just after midnight, the famous Orient Express is stopped in its tracks by a snowdrift. By morning, the millionaire Samuel Edward Ratchett lies dead in his compartment, stabbed a dozen times, his door locked from the inside. Without a shred of doubt, one of his fellow passengers is the murderer. Isolated by the storm, detective Hercule Poirot must find the killer among a dozen of the dead man’s enemies, before the murderer decides to strike again.', price: 14.39, image: 'assets/book4.jpg', rating: 25, ratingsCount: 5 },
    { id: 5, title: 'The Maze Runner', author: 'James Dashner', category: 'Novel', pageNumber: 400, publishingYear: 2010, description: 'When Thomas wakes up in the lift, the only thing he can remember is his name. He’s surrounded by strangers—boys whose memories are also gone. Outside the towering stone walls that surround them is a limitless, ever-changing maze. It’s the only way out—and no one’s ever made it through alive. Then a girl arrives. The first girl ever. And the message she delivers is terrifying: Remember. Survive. Run.', price: 17.95, image: 'assets/book5.jpg', rating: 29, ratingsCount: 6 },
    { id: 6, title: 'The Underworld', author: 'Susan Casey', category: 'Science', pageNumber: 352, publishingYear: 2023, description: 'For all of human history, the deep ocean has been a source of wonder and terror, an unknown realm that evoked a singular, compelling question: What’s down there? Unable to answer this for centuries, people believed the deep was a sinister realm of fiendish creatures and deadly peril. But now, cutting-edge technologies allow scientists and explorers to dive miles beneath the surface, and we are beginning to understand this strange and exotic underworld:  A place of soaring mountains, smoldering volcanoes, and valleys 7,000 feet deeper than Everest is high, where tectonic plates collide and separate, and extraordinary life forms operate under different rules. Far from a dark void, the deep is a vibrant realm that’s home to pink gelatinous predators and shimmering creatures a hundred', price: 24.99, image: 'assets/book6.jpg' },
    { id: 7, title: 'The Island', author: 'Natasha Preston', category: 'Thriller', pageNumber: 336, publishingYear: 2023, description: 'They said goodbye to their friends and family for the weekend. They weren’t counting on forever. Jagged Island: a private amusement park for the very rich—or the very influential. Liam, James, Will, Ava, Harper, and Paisley—social media influencers with millions of followers—have been invited for an exclusive weekend before the park opens. They’ll make posts and videos for their channels and report every second of their VIP treatment. When the teens arrive, theyre stunned: the resort is even better than theyd imagined. Their hotel rooms are unreal, the park’s themed rides are incredible, and the island is hauntingly beautiful. They’re given a jam-packed itinerary for the weekend. But soon theyll discover that somethings missing from their schedule: getting off the island alive', price: 9.47, image: 'assets/book7.jpg', rating: 4, ratingsCount: 1 },
    { id: 8, title: 'Scattered Minds', author: 'Gabor Mate', category: 'Science', pageNumber: 200, publishingYear: 2023, description: 'New York Times bestseller! From renowned mental health expert and speaker Dr. Gabor Maté, Scattered Minds explodes the myth of attention deficit disorder (ADD/ADHD) as genetically based—and offers real hope and advice for children and adults who live with the condition. In this breakthrough guide to understanding, treating, and healing Attention Deficit Disorder, Dr. Gabor Maté, best-selling author of The Myth of Normal, and himself diagnosed with ADD. Whereas other books on the subject describe the condition as inherited, Dr. Maté believes that our social and emotional environments play a key role in both the cause of and cure for this condition. In Scattered Minds, he describes the painful realities of ADD and its effect on children as well as on career and social paths in adults.', price: 10.99, image: 'assets/book8.jpg', rating: 9, ratingsCount: 2 },
    { id: 9, title: 'Why We Sleep', author: 'Matthew Walker', category: 'Science', pageNumber: 368, publishingYear: 2017, description: 'Sleep is one of the most important but least understood aspects of our life, wellness, and longevity. Until very recently, science had no answer to the question of why we sleep, or what good it served, or why we suffer such devastating health consequences when we dont sleep. Compared to the other basic drives in life—eating, drinking, and reproducing—the purpose of sleep remained elusive. An explosion of scientific discoveries in the last twenty years has shed new light on this fundamental aspect of our lives. Now, preeminent neuroscientist and sleep expert Matthew Walker gives us a new understanding of the vital importance of sleep and dreaming. Within the brain, sleep enriches our ability to learn, memorize, and make logical decisions. It recalibrates our emotions, restocks our immune system, fine-tunes our metabolism, and regulates our appetite. Dreaming mollifies painful memories and creates a virtual reality space in which the brain melds past and present knowledge to inspire creativity.', price: 19.39, image: 'assets/book9.jpg' },
    { id: 10, title: 'It Starts With Us', author: 'Colleen Hoover', category: 'Romance', pageNumber: 360, publishingYear: 2022, description: 'Before It Ends with Us, it started with Atlas. Colleen Hoover tells fan favorite Atlas’s side of the story and shares what comes next in this long-anticipated sequel to the “glorious and touching” (USA TODAY) #1 New York Times bestseller It Ends with Us. Lily and her ex-husband, Ryle, have just settled into a civil coparenting rhythm when she suddenly bumps into her first love, Atlas, again. After nearly two years separated, she is elated that for once, time is on their side, and she immediately says yes when Atlas asks her on a date. But her excitement is quickly hampered by the knowledge that, though they are no longer married, Ryle is still very much a part of her life—and Atlas Corrigan is the one man he will hate being in his ex-wife and daughter’s life.', price: 10.69, image: 'assets/book10.jpg', rating: 3, ratingsCount: 1 },
    { id: 11, title: '$100M Offers', author: 'Alex Hormozi', category: 'Business', pageNumber: 350, publishingYear: 2021, description: 'I took home more in a year than the CEOs of McDonalds, IKEA, Ford, Motorola, and Yahoo combined as a kid in my 20s using the $100M Offers method. It works. And it will work for you. Not that long ago, though, my business had gotten so bad that I literally couldn’t even give my services away for free. At the end of each month, I would look at my bank account hoping to see progress (but there wasn’t). I knew something had to change...but what? Over the next 48 months, I went from losing money to making $36 for every $1 spent. In that time period, we generated over $120,000,000 across four different industries: service, ecommerce, software, and brick and mortar. But, unlike everyone else, we didn’t have great funnels, great ads, or a wealthy niche. In fact, we didn’t even send emails until we had crossed $50M in sales. Instead, we were able to do this one thing really well: We created offers so good, people felt stupid saying no.', price: 9.99, image: 'assets/book11.png', rating: 5, ratingsCount: 1 },
    { id: 12, title: 'Inception', author: 'Christopher Nolan', category: 'Thriller', pageNumber: 240, publishingYear: 2010, description: 'Inception, writer-director Christopher Nolan’s seventh feature film, joins the epic scope of The Dark Knight with the narrative sophistication of Memento. The story of a group of thieves who specialize in invading the mind through one’s dreams, Inception explores the Nolan’s signature psychological themes of memory, paranoia, and self-doubt as the protagonist, Dom Cobb, is pitted against a hostile subconscious spurred on by personal demons and regrets from the past. In a conversational preface, Nolan discusses with brother and frequent collaborator, Jonah, the genesis of the idea for the film and the decade-long process it took to write it. Detailing the results of Nolan’s efforts, Inception: The Shooting Script includes key storyboard sequences, full-color concept art, and an appendix on the workings of the mysterious Pasiv Device that Cobb and his fellow extractors use to initiate the dream-share. An exclusive exploration of a highly original concept, Inception: The Shooting Script is the record of a writer-director at the height of his craft.', price: 26.99, image: 'assets/book12.jpg' }
  ];

  getBooks(orderBy: string = ''): BookModel[] {
    let sortedBooks = this.books;
    if (orderBy === 'title') {
      sortedBooks = sortedBooks.sort((a, b) => a.title.localeCompare(b.title));
    } else if (orderBy === 'author') {
      sortedBooks = sortedBooks.sort((a, b) => a.author.localeCompare(b.author));
    } else if (orderBy === 'price') {
      sortedBooks = sortedBooks.sort((a, b) => a.price - b.price);
    }
    return sortedBooks;
  }

  getBookById(id: number): BookModel | undefined {
    return this.books.find(book => book.id === id);
  }

  public filteredBooks: Book[] = [];

  performSearch(searchQuery: string): void {
    const lowerCaseSearchQuery = searchQuery.toLowerCase();
    this.filteredBooks = this.books.filter((book) => {
      return (
        book.title.toLowerCase().includes(lowerCaseSearchQuery) ||
        book.author.toLowerCase().includes(lowerCaseSearchQuery) ||
        book.description.toLowerCase().includes(lowerCaseSearchQuery)
      );
    });
  }
}
